name: Integration tests
run-name: ${{ github.actor }} is testing out integrations outputs
on: [push]
jobs:
  test-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set deprecated output
        id: test-deprecated-action
        run: echo "::set-output name=TEST1::value1"
      - name: Get deprecated output
        run: echo "The deprecated output is ${{ steps.test-deprecated-action.outputs.TEST1}}"
      - name: Set output
        id: test-action
        run: echo "TEST2=value2" >> $GITHUB_OUTPUT
      - name: Get output
        run: echo "The output is ${{ steps.test-action.outputs.TEST2}}"
      - name: Set deprecated output by script
        id: script-dep-out
        run: |
          chmod +x ./.github/scripts/test_dep.sh
          ./.github/scripts/test_dep.sh
      - name: Get dobs out
        run: echo "The output is ${{ steps.script-dep-out.outputs.TEST3}}"
      - name: Set output by script
        id: script-out
        run: |
          chmod +x ./.github/scripts/test.sh
          ./.github/scripts/test.sh
      - name: Get obs out
        run: echo "The output is ${{ steps.script-out.outputs.TEST4}}"
    outputs:
      test_outputs: ${{ steps.script-out.outputs.TEST4 }}
  get-github-var:
    runs-on: ubuntu-latest
    needs: [test-github-actions]
    steps:
      - name: test_outputs
        run: echo "The output is ${{ needs.test-github-actions.outputs.test_outputs }}"
