name: Integration tests
run-name: ${{ github.actor }} is testing out integrations outputs
on: [push]
jobs:
  test-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set deprecated output
        id: test-deprecated-action
        run: echo "::set-output name=TEST1::value1"
      - name: Get deprecated output
        run: echo "The deprecated output is ${{ steps.test-deprecated-action.outputs.TEST1}}"
      - name: Set output
        id: test-action
        run: echo "TEST2=value2" >> $GITHUB_OUTPUT
      - name: Get output
        run: echo "The output is ${{ steps.test-action.outputs.TEST2}}"
